server.port=${PORT:8080}
spring.application.name=conferencia

# URL SIN credenciales
spring.datasource.url=jdbc:postgresql://ep-bitter-resonance-at24lonp-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require

# CREDENCIALES SEPARADAS
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XkaW2dH1cIDE
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraciones simplificadas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true